import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container flex justify-center">
        {session?.user ? (
          <button className="btn" onClick={() => signOut()}>
            sign out
          </button>
        ) : (
          <button className="btn" onClick={() => signIn()}>
            sign in
          </button>
        )}
        <h2 className="text-xl text-white">
          {session?.user?.name && `Log In as ${session.accessToken}`}
        </h2>
      </div>
    </>
  );
};

export default Home;
